export const keySymbolsWin: { [key: string]: string } = {
  shift: '⇧',
  option: 'Alt',
  alt: 'Alt',
  control: 'Ctrl',
  ctrl: 'Ctrl',
  return: '↵',
  enter: '↵',
  left: '←',
  right: '→',
  up: '↑',
  down: '↓',
  backspace: '⌫',
  delete: 'Del',
  escape: 'Esc',
  esc: 'Esc',

  plus: '+',
  minus: '-',
  bracketleft: '[',
  bracketright: ']',
  braceleft: '{',
  braceright: '}',
  backslash: '\\',
  slash: '/',
  period: '.',
  comma: ',',
  semicolon: ';',
  quote: "'",
  backquote: '`',
  equal: '=',
};
